site_name: FOM.tft-timeseries – Notizen
site_description: Projektdokumentation, Dev Notes und Konfiguration
theme:
  name: material
  language: de
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - content.tabs.link
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - attr_list

nav:
  - Übersicht: index.md
  - Projekt Pipeline:
      - Pipeline & I/O: project/PipelineOrder.md

  - Projekt Schritte:
      - Data Preprocessing:
        - Data Alignment: project/DataAlignment.md
        - Data Cleaning: project/DataCleaning.md
        - Data Cleaning Plot: project/DataCleaningPlot.md
        - Feature Engineering: project/FeatureEngineer.md
        - Cyclical Encoder: project/CyclicalEncoder.md
        - Lag Features: project/LagFeatures.md
      - Modeling:
        - Dataset TFT: project/DatasetTFT.md
        - Model Dataset: project/ModelDataset.md
        - Trainer TFT: project/TrainerTFT.md
        - Trainer TFT – Runprotokoll: project/TrainerTFT_Runprotokoll.md
  - Allgemeine Dokumentation:
      - Projektstruktur: shared/Projektstruktur.md
      - Configs & Setup: shared/ConfigSetup.md
      - Trainer & Evaluator Struktur: project/TrainerEvaluator_Stuktur.md
      - MkDocs Nutzung: shared/MkDocsUsage.md